# Generated by Django 4.1.1 on 2023-07-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
